Traceback (most recent call last):
  File "/home/pi/python_scripts/DataLoggerSystem/serial_read.py", line 27, in <module>
    moving_filter[moving_filter_ptr] = float(data)
IndexError: list assignment index out of range
